### ISSUE TITLE
How Does It Works 

### ISSUE THREAD

**Issue by mauryarahul8139** [roccomuso/price-monitoring#4]
While Importing the  Command that you have Mentioned Need To Install npm install --save price-monitoring while hitting the enter it showing that :
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "price-monitoring" under a package      
npm ERR! also called "price-monitoring". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RAHUL\AppData\Roaming\npm-cache\_logs\2022-04-15T07_30_22_193Z-debug.log

**Comment by roccomuso** [comment]
this is the package to install: https://www.npmjs.com/package/price-monitoring
